### ISSUE TITLE
ProtocolError: packet is not EOF

### ISSUE THREAD

**Issue by ttosch** [maxlapshin/mysql2postgres#71]
I am getting the following error when running in my local setup (mysql 5.5.40, ruby 2.1.5 on ubuntu 14.04):

```
$ mysql --version
mysql  Ver 14.14 Distrib 5.5.40, for debian-linux-gnu (x86_64) using readline 6.3
```

```
$ RAILS_ENV=production mysqltopostgres database.yml
gems/mysql-pr-2.9.11/lib/mysql-pr/protocol.rb:562:in `read_eof_packet': packet is not EOF (MysqlPR::ProtocolError)
        from gems/mysql-pr-2.9.11/lib/mysql-pr/protocol.rb:274:in `retr_fields'
        from gems/mysql-pr-2.9.11/lib/mysql-pr.rb:322:in `query'
        from gems/mysql-pr-2.9.11/lib/mysql-pr.rb:442:in `list_tables'
        from bundler/gems/mysql2postgres-084519061f48/lib/mysql2psql/mysql_reader.rb:193:in `tables'
        from bundler/gems/mysql2postgres-084519061f48/lib/mysql2psql/converter.rb:21:in `convert'
        from bundler/gems/mysql2postgres-084519061f48/lib/mysqltopostgres.rb:51:in `convert'
        from bundler/gems/mysql2postgres-084519061f48/bin/mysqltopostgres:23:in `<top (required)>'
        from bin/mysqltopostgres:23:in `load'
        from bin/mysqltopostgres:23:in `<main>'
        from bin/ruby_executable_hooks:15:in `eval'
        from bin/ruby_executable_hooks:15:in `<main>'
```

MySQL config (nothing special):

```
[...]
mysql_data_source: &pii
  hostname: localhost
  port: 3306
  socket: /var/run/mysqld/mysqld.sock
  username: xx
  password: xx
  database: xx

mysql2psql:
  mysql:
    <<: *pii

[...]
```

Thanks!
Thomas
