### ISSUE TITLE
`require': cannot load such file -- bundler/setup (LoadError)

### ISSUE THREAD

**Issue by pathikrit** [maxlapshin/mysql2postgres#89]
Installation:

```
↪  gem install mysqltopostgres                                                                                                                                                                                                                                                             Wed Feb  3 16:54:32 PST 2016
Fetching: i18n-0.7.0.gem (100%)
Successfully installed i18n-0.7.0
Fetching: thread_safe-0.3.5.gem (100%)
Successfully installed thread_safe-0.3.5
Fetching: tzinfo-1.2.2.gem (100%)
Successfully installed tzinfo-1.2.2
Fetching: activesupport-4.2.5.1.gem (100%)
Successfully installed activesupport-4.2.5.1
Fetching: builder-3.2.2.gem (100%)
Successfully installed builder-3.2.2
Fetching: activemodel-4.2.5.1.gem (100%)
Successfully installed activemodel-4.2.5.1
Fetching: arel-6.0.3.gem (100%)
Successfully installed arel-6.0.3
Fetching: activerecord-4.2.5.1.gem (100%)
Successfully installed activerecord-4.2.5.1
Fetching: activerecord-jdbc-adapter-1.3.19.gem (100%)
Successfully installed activerecord-jdbc-adapter-1.3.19
Fetching: jdbc-postgres-9.4.1204.gem (100%)
Successfully installed jdbc-postgres-9.4.1204
Fetching: activerecord-jdbcpostgresql-adapter-1.3.19.gem (100%)
Successfully installed activerecord-jdbcpostgresql-adapter-1.3.19
Fetching: jdbc-sqlite3-3.8.11.2.gem (100%)
Successfully installed jdbc-sqlite3-3.8.11.2
Fetching: activerecord-jdbcsqlite3-adapter-1.3.19.gem (100%)
Successfully installed activerecord-jdbcsqlite3-adapter-1.3.19
Fetching: mysql-pr-2.9.11.gem (100%)
Successfully installed mysql-pr-2.9.11
Fetching: postgres-pr-0.6.3.gem (100%)
Successfully installed postgres-pr-0.6.3
Fetching: mysqltopostgres-0.2.15.gem (100%)
Successfully installed mysqltopostgres-0.2.15
Parsing documentation for i18n-0.7.0
Installing ri documentation for i18n-0.7.0
Parsing documentation for thread_safe-0.3.5
Installing ri documentation for thread_safe-0.3.5
Parsing documentation for tzinfo-1.2.2
Installing ri documentation for tzinfo-1.2.2
Parsing documentation for activesupport-4.2.5.1
Installing ri documentation for activesupport-4.2.5.1
Parsing documentation for builder-3.2.2
Installing ri documentation for builder-3.2.2
Parsing documentation for activemodel-4.2.5.1
Installing ri documentation for activemodel-4.2.5.1
Parsing documentation for arel-6.0.3
Installing ri documentation for arel-6.0.3
Parsing documentation for activerecord-4.2.5.1
Installing ri documentation for activerecord-4.2.5.1
invalid options: -SHN
(invalid options are ignored)
Parsing documentation for activerecord-jdbc-adapter-1.3.19
Installing ri documentation for activerecord-jdbc-adapter-1.3.19
Parsing documentation for jdbc-postgres-9.4.1204
Installing ri documentation for jdbc-postgres-9.4.1204
Parsing documentation for activerecord-jdbcpostgresql-adapter-1.3.19
Installing ri documentation for activerecord-jdbcpostgresql-adapter-1.3.19
Parsing documentation for jdbc-sqlite3-3.8.11.2
Installing ri documentation for jdbc-sqlite3-3.8.11.2
Parsing documentation for activerecord-jdbcsqlite3-adapter-1.3.19
Installing ri documentation for activerecord-jdbcsqlite3-adapter-1.3.19
Parsing documentation for mysql-pr-2.9.11
Installing ri documentation for mysql-pr-2.9.11
Parsing documentation for postgres-pr-0.6.3
Installing ri documentation for postgres-pr-0.6.3
Parsing documentation for mysqltopostgres-0.2.15
Installing ri documentation for mysqltopostgres-0.2.15
Done installing documentation for i18n, thread_safe, tzinfo, activesupport, builder, activemodel, arel, activerecord, activerecord-jdbc-adapter, jdbc-postgres, activerecord-jdbcpostgresql-adapter, jdbc-sqlite3, activerecord-jdbcsqlite3-adapter, mysql-pr, postgres-pr, mysqltopostgres after 36 seconds
16 gems installed
```

My config:

```
default: &default
  adapter: jdbcpostgresql
  encoding: unicode
  pool: 4
  username: dev
  password: dev
  host: 127.0.0.1

development: &development
  <<: *default
  database: main

test: &test
  <<: *default
  database: main

production: &production
  <<: *default
  database: main

mysql_data_source: &pii
  hostname: localhost
  port: 3306
  socket: /tmp/mysqld.sock
  username: dev
  password: dev
  database: main

mysql2psql:
  mysql:
    <<: *pii

  destination:
    production:
      <<: *production
    test:
      <<: *test
    development:
      <<: *development

  tables:

  # If suppress_data is true, only the schema definition will be exported/migrated, and not the data
  suppress_data: false

  # If suppress_ddl is true, only the data will be exported/imported, and not the schema
  suppress_ddl: false

  # If force_truncate is true, forces a table truncate before table loading
  force_truncate: false

  preserve_order: true

  remove_dump_file: true

  dump_file_directory: /tmp

  report_status: json    # false, json, xml

  # If clear_schema is true, the public schema will be recreated before conversion
  # The import will fail if both clear_schema and suppress_ddl are true.
  clear_schema: false
```

Error:

```
mysqltopostgres ~/Projects/gandalf/scripts/postgres/test.yaml                                                                                                                                                                                                                           Wed Feb  3 17:03:17 PST 2016
/usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bundler/setup (LoadError)
    from /usr/local/Cellar/ruby/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /usr/local/lib/ruby/gems/2.2.0/gems/mysqltopostgres-0.2.15/bin/mysqltopostgres:5:in `<top (required)>'
    from /usr/local/bin/mysqltopostgres:23:in `load'
    from /usr/local/bin/mysqltopostgres:23:in `<main>'
```
